import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Footer from "@/components/footer";







export const metadata = {
  title: 'Piton Technology Case Study',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="box-border">

        <div className='flex flex-col'>

          {children}
          <Footer />
        </div>
      </body>

    </html>
  )
}
